version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Avrora/ :/usr/src/Avrora/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scandinavian
      - POSTGRES_PASSWORD=Panda312
      - POSTGRES_DB=avrora
volumes:
  postgres_data:
