version: '3.9'
services:
  web:
    restart: always
    build: ./web
    command: gunicorn task32admin.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - static_volume:/usr/src/web/staticfiles
    expose:
      - 8004
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/web/staticfiles
    ports:
      - "8003:8003"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
